import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";
import { Suspense } from "react";
import Loading from "./loading/page";
import { AgencyAuthProvider } from "@/context/AgencyAuthContext";


export const metadata: Metadata = {
  title: "MVP Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </head>
      <body>
        <Suspense fallback={<Loading />}>
          <AgencyAuthProvider>
            <AuthContextProvider>
              {children}
              <Toaster position="top-center" />
            </AuthContextProvider>
          </AgencyAuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
