import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";
 

export const metadata: Metadata = {
  title: "MVP Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </head>
      <body>
        <AuthContextProvider>
           {children}
           <Toaster/>
        </AuthContextProvider>
       
      </body>
    </html>
  );
}
